# Make sure the .env file is ready and has the correct values
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # Check if we want to expose this port to the host
    env_file:
      - ./core/.env
  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  cdn:
    image: nginx:1.25.3
    restart: always
    ports:
      - "6464:80"
    env_file:
      - ./core/.env
    volumes:
      - ${HOST_CDN_DIR}:/usr/share/nginx/html:Z
  api.core:
    image: apicore
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - "8081:8080"
      - "8082:8081"
    env_file:
      - ./core/.env
volumes:
  cache:
    driver: local
