## Run this file after running the one presented in the database setup repository
## https://github.com/ApplETS/Hello-Database-Setup
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
      - "8082:8081"
    networks:
      - hello-database-setup_default
networks:
  hello-database-setup_default:
    external: true