// <auto-generated />
using System;
using HelloAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelloAPI.Migrations
{
    [DbContext(typeof(EventManagementContext))]
    partial class EventManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelloAPI.Data.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Moderator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.HasKey("Id");

                    b.ToTable("Moderator");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Organizer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivityArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.HasKey("Id");

                    b.ToTable("Organizer");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Publication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ModeratorId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ModeratorId" }, "IX_Publication_ModeratorId");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_Publication_OrganizerId");

                    b.ToTable("Publication");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Report", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PublicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PublicationId" }, "IX_Report_PublicationId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriorityValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(now() AT TIME ZONE 'utc'::text)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("PublicationTag", b =>
                {
                    b.Property<long>("PublicationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TagsId")
                        .HasColumnType("bigint");

                    b.HasKey("PublicationsId", "TagsId");

                    b.HasIndex(new[] { "TagsId" }, "IX_PublicationTag_TagsId");

                    b.ToTable("PublicationTag", (string)null);
                });

            modelBuilder.Entity("TagTag", b =>
                {
                    b.Property<long>("ChildrenTagsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentTagsId")
                        .HasColumnType("bigint");

                    b.HasKey("ChildrenTagsId", "ParentTagsId");

                    b.ToTable("TagTag");
                });

            modelBuilder.Entity("TagsHierarchy", b =>
                {
                    b.Property<long>("ChildrenTagsId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentTagsId")
                        .HasColumnType("bigint");

                    b.HasKey("ChildrenTagsId", "ParentTagsId");

                    b.HasIndex(new[] { "ParentTagsId" }, "IX_TagsHierarchy_ParentTagsId");

                    b.ToTable("TagsHierarchy", (string)null);
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Event", b =>
                {
                    b.HasOne("HelloAPI.Data.Entities.Publication", "IdNavigation")
                        .WithOne("Event")
                        .HasForeignKey("HelloAPI.Data.Entities.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Publication", b =>
                {
                    b.HasOne("HelloAPI.Data.Entities.Moderator", "Moderator")
                        .WithMany("Publications")
                        .HasForeignKey("ModeratorId")
                        .HasConstraintName("Publication_ModeratorId_fkey");

                    b.HasOne("HelloAPI.Data.Entities.Organizer", "Organizer")
                        .WithMany("Publications")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Publication_OrganizerId_fkey");

                    b.Navigation("Moderator");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Report", b =>
                {
                    b.HasOne("HelloAPI.Data.Entities.Publication", "Publication")
                        .WithMany("Reports")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Report_PublicationId_fkey");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PublicationTag", b =>
                {
                    b.HasOne("HelloAPI.Data.Entities.Publication", null)
                        .WithMany()
                        .HasForeignKey("PublicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloAPI.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagsHierarchy", b =>
                {
                    b.HasOne("HelloAPI.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("ChildrenTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelloAPI.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("ParentTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Moderator", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Organizer", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("HelloAPI.Data.Entities.Publication", b =>
                {
                    b.Navigation("Event");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
