name: Build .NET APP

on:
  push:
    branches: 
      - "main"
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  AZURE_RES_GROUP: Hello
  AZURE_CONTAINER_APP: backend-hello

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Login to Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Login to Azure
        if: startsWith(github.ref, 'refs/tags/v')
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Remove 'v' from tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: remove_v
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\/v/}"

      - name: Set new image tag for Azure Container App
        if: startsWith(github.ref, 'refs/tags/v')
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az containerapp update --name ${{ env.AZURE_CONTAINER_APP }} --resource-group ${{ env.AZURE_RES_GROUP }} --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.remove_v.outputs.tag }} }}
